from datetime import datetime
from decimal import Decimal

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session, joinedload

from app.core.deps import get_current_user, require_role
from app.db.session import get_db
from app.models.models import (
    User, RoleEnum, Order, OrderItem, OrderStatusEnum, Payment, PaymentMethodEnum, PaymentStatusEnum
)
from app.schemas.schemas import PaymentVerifyIn, PaymentQrConfirmIn, PaymentFailIn, SettlementOut, OrderOut
from app.services.payment_service import verify_razorpay_signature, calculate_settlement_breakdown
from app.routers.orders import _serialize_order, dispatch_order_fulfillment

router = APIRouter(prefix="/api/payments", tags=["payments"])


@router.post("/confirm-qr", response_model=OrderOut)
def confirm_qr_payment(
    payload: PaymentQrConfirmIn,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """
    Confirms direct UPI QR payment (scanned via Google Pay, PhonePe, Paytm, BHIM, etc.):
      - payment_method = "UPI"
      - payment_status = "PAID"
      - order_status = "CONFIRMED"
      - gateway = "UPI_QR"
      - gateway_payment_id = utr_number or autogenerated ref
      - triggers dispatch_order_fulfillment (batching, transporter allocation, notifications)
    Guarantees idempotency.
    """
    order = (
        db.query(Order)
        .options(joinedload(Order.items).joinedload(OrderItem.listing), joinedload(Order.payment))
        .filter(Order.id == payload.order_id)
        .with_for_update()
        .first()
    )
    if not order:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"Order #{payload.order_id} not found")

    if user.role != RoleEnum.admin:
        if not user.buyer_profile or order.buyer_id != user.buyer_profile.id:
            raise HTTPException(status.HTTP_403_FORBIDDEN, "Not authorized to confirm payment for this order")

    # Idempotency check
    if order.payment_status == PaymentStatusEnum.PAID:
        return _serialize_order(order)

    now = datetime.utcnow()
    order.payment_method = PaymentMethodEnum.UPI
    order.payment_status = PaymentStatusEnum.PAID
    order.status = OrderStatusEnum.CONFIRMED
    order.paid_at = now

    tx_ref = payload.utr_number.strip() if payload.utr_number and payload.utr_number.strip() else f"UPI_QR_{order.id}_{int(now.timestamp())}"

    if order.payment:
        order.payment.payment_status = PaymentStatusEnum.PAID
        order.payment.gateway = "UPI_QR"
        order.payment.gateway_payment_id = tx_ref
        order.payment.paid_at = now
    else:
        order.payment = Payment(
            order_id=order.id,
            amount=order.total_amount,
            currency="INR",
            payment_method=PaymentMethodEnum.UPI,
            payment_status=PaymentStatusEnum.PAID,
            gateway="UPI_QR",
            gateway_payment_id=tx_ref,
            farmer_amount=order.farmer_settlement_amount,
            transporter_amount=order.transporter_settlement_amount,
            commission_amount=order.platform_commission_amount,
            paid_at=now,
        )
        db.add(order.payment)

    # Dispatch delivery fulfillment and transport jobs now that payment is confirmed
    dispatch_order_fulfillment(db, order)

    db.commit()
    db.refresh(order)
    return _serialize_order(order)


@router.post("/verify", response_model=OrderOut)
def verify_payment(
    payload: PaymentVerifyIn,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """
    Verifies the Razorpay payment signature server-side.
    Only after successful verification:
      - payment_method = "UPI"
      - payment_status = "PAID"
      - order_status = "CONFIRMED"
      - creates delivery batches & fulfillment items
    Guarantees idempotency and prevents race conditions.
    """
    order = (
        db.query(Order)
        .options(joinedload(Order.items).joinedload(OrderItem.listing), joinedload(Order.payment))
        .filter(Order.id == payload.order_id)
        .with_for_update()
        .first()
    )
    if not order:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"Order #{payload.order_id} not found")

    # Access control: buyer who placed the order or admin
    if user.role != RoleEnum.admin:
        if not user.buyer_profile or order.buyer_id != user.buyer_profile.id:
            raise HTTPException(status.HTTP_403_FORBIDDEN, "Not authorized to verify payment for this order")

    # Idempotency check
    if order.payment_status == PaymentStatusEnum.PAID:
        return _serialize_order(order)

    # Server-side cryptographic signature verification
    is_valid = verify_razorpay_signature(
        razorpay_order_id=payload.razorpay_order_id,
        razorpay_payment_id=payload.razorpay_payment_id,
        razorpay_signature=payload.razorpay_signature,
    )
    if not is_valid:
        if order.payment:
            order.payment.payment_status = PaymentStatusEnum.FAILED
        order.payment_status = PaymentStatusEnum.FAILED
        db.commit()
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "Razorpay signature verification failed. Untrusted payment attempt."
        )

    # Transition payment & order status to PAID / CONFIRMED
    now = datetime.utcnow()
    order.payment_method = PaymentMethodEnum.UPI
    order.payment_status = PaymentStatusEnum.PAID
    order.status = OrderStatusEnum.CONFIRMED
    order.paid_at = now

    if order.payment:
        order.payment.payment_status = PaymentStatusEnum.PAID
        order.payment.gateway_payment_id = payload.razorpay_payment_id
        order.payment.gateway_signature = payload.razorpay_signature
        order.payment.paid_at = now
    else:
        order.payment = Payment(
            order_id=order.id,
            amount=order.total_amount,
            currency="INR",
            payment_method=PaymentMethodEnum.UPI,
            payment_status=PaymentStatusEnum.PAID,
            gateway="RAZORPAY",
            gateway_order_id=payload.razorpay_order_id,
            gateway_payment_id=payload.razorpay_payment_id,
            gateway_signature=payload.razorpay_signature,
            farmer_amount=order.farmer_settlement_amount,
            transporter_amount=order.transporter_settlement_amount,
            commission_amount=order.platform_commission_amount,
            paid_at=now,
        )
        db.add(order.payment)

    # Only activate delivery fulfillment and transport jobs AFTER payment is verified!
    dispatch_order_fulfillment(db, order)

    db.commit()
    db.refresh(order)
    return _serialize_order(order)


@router.post("/fail")
def fail_payment(
    payload: PaymentFailIn,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """
    Handles payment failure or user cancellation:
      - payment_status = "FAILED"
      - order_status = "CANCELLED"
      - restores produce inventory immediately
      - no delivery jobs are activated
    """
    order = (
        db.query(Order)
        .options(joinedload(Order.items).joinedload(OrderItem.listing), joinedload(Order.payment))
        .filter(Order.id == payload.order_id)
        .with_for_update()
        .first()
    )
    if not order:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"Order #{payload.order_id} not found")

    if user.role != RoleEnum.admin:
        if not user.buyer_profile or order.buyer_id != user.buyer_profile.id:
            raise HTTPException(status.HTTP_403_FORBIDDEN, "Not authorized to update payment for this order")

    if order.payment_status == PaymentStatusEnum.PAID:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Cannot fail an already paid order")

    order.payment_status = PaymentStatusEnum.FAILED
    order.status = OrderStatusEnum.CANCELLED
    if order.payment:
        order.payment.payment_status = PaymentStatusEnum.FAILED

    # Restore inventory
    for item in order.items:
        if item.listing:
            item.listing.quantity_available += item.quantity
            item.listing.is_active = True

    db.commit()
    return {
        "success": True,
        "order_id": order.id,
        "payment_status": "FAILED",
        "order_status": "CANCELLED",
        "message": "Payment failed or cancelled. Produce inventory has been restored.",
    }


@router.post("/orders/{order_id}/collect-cod", response_model=OrderOut)
def collect_cod_payment(
    order_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(require_role(RoleEnum.transporter, RoleEnum.admin)),
):
    """
    Transporter or admin records Pay on Delivery collection upon doorstep delivery.
    Transitions payment_status from PENDING to PAID.
    """
    order = (
        db.query(Order)
        .options(joinedload(Order.items).joinedload(OrderItem.listing), joinedload(Order.payment))
        .filter(Order.id == order_id)
        .with_for_update()
        .first()
    )
    if not order:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"Order #{order_id} not found")

    if order.payment_method != PaymentMethodEnum.PAY_ON_DELIVERY:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            f"Order #{order_id} was placed via {order.payment_method}, not Pay on Delivery."
        )

    now = datetime.utcnow()
    order.payment_status = PaymentStatusEnum.PAID
    order.paid_at = now
    if order.payment:
        order.payment.payment_status = PaymentStatusEnum.PAID
        order.payment.paid_at = now

    db.commit()
    db.refresh(order)
    return _serialize_order(order)


@router.get("/orders/{order_id}/settlement", response_model=SettlementOut)
def get_order_settlement(
    order_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """
    Returns settlement breakdown:
    - Farmer amount: produce subtotal
    - Transporter amount: logistics fee
    - Platform commission: 2% AgriDirect platform fee
    """
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"Order #{order_id} not found")

    return SettlementOut(
        order_id=order.id,
        total_amount=order.total_amount,
        payment_method=order.payment_method,
        payment_status=order.payment_status,
        paid_at=order.paid_at,
        farmer_amount=order.farmer_settlement_amount,
        transporter_amount=order.transporter_settlement_amount,
        commission_amount=order.platform_commission_amount,
    )

